const matchData = [
  	{
    "season": "1415",
    "leagueTitle": "Mens Leinster Senior League Division 1",
    "league": "1",
    "title": "Corinthian &#8211; Railway Union",
    "homeTeam": "Corinthian",
    "awayTeam": "Railway Union",
    "score": "1 - 2",
    "location": "Whitechurch Park",
    "matchDate": "2015-01-24",
    "displayDate": "24-01-2015",
    "parsedDate": "2015, 01, 24",
    "startTime": "2:15 pm"
	  },
    {
    "season": "1415",
    "leagueTitle": "Mens Division Four",
    "league": "10",
    "title": "Corinthian III &#8211; Naas",
    "homeTeam": "Corinthian III",
    "awayTeam": "Naas",
    "score": "1 - 0",
    "location": "Whitechurch Park",
    "matchDate": "2015-02-14",
    "displayDate": "14-02-2015",
    "parsedDate": "2015, 02, 14",
    "startTime": "11:15 am"
  },
{
    "season": "1415",
    "leagueTitle": "Womens Division Twelve",
    "league": "25",
    "title": "Wicklow &#8211; Clontarf V",
    "homeTeam": "Wicklow",
    "awayTeam": "Clontarf V",
    "score": "1 - 0",
    "location": "East Glendalough",
    "matchDate": "2015-02-17",
    "displayDate": "17-02-2015",
    "parsedDate": "2015, 02, 17",
    "startTime": ""
  },
  {
    "season": "1415",
    "leagueTitle": "Womens Division Four",
    "league": "17",
    "title": "Loreto III &#8211; Pembroke IV",
    "homeTeam": "Loreto III",
    "awayTeam": "Pembroke IV",
    "score": "1 - 0",
    "location": "Beaufort",
    "matchDate": "2014-10-18",
    "displayDate": "18-10-2014",
    "parsedDate": "2014, 10, 18",
    "startTime": "2:30 pm"
  },
  {
    "season": "1415",
    "leagueTitle": "Mens Division Three",
    "league": "9",
    "title": "TRR III &#8211; Rathgar II",
    "homeTeam": "TRR III",
    "awayTeam": "Rathgar II",
    "score": "5 - 1",
    "location": "Grange Road",
    "matchDate": "2014-12-06",
    "displayDate": "06-12-2014",
    "parsedDate": "2014, 12, 06",
    "startTime": ""
  },
  {
    "season": "1415",
    "leagueTitle": "Mens Division 2",
    "league": "4",
    "title": "Corinthian II &#8211; Monkstown II",
    "homeTeam": "Corinthian II",
    "awayTeam": "Monkstown II",
    "score": "2 - 6",
    "location": "Whitechurch Park",
    "matchDate": "2015-03-14",
    "displayDate": "14-03-2015",
    "parsedDate": "2015, 03, 14",
    "startTime": "11:15 am"
  },
   {
    "season": "1415",
    "leagueTitle": "Mens Division Seven",
    "league": "13",
    "title": "Monkstown V &#8211; Corinthian IV",
    "homeTeam": "Monkstown V",
    "awayTeam": "Corinthian IV",
    "score": "5 - 0",
    "location": "Rathdown",
    "matchDate": "2014-10-04",
    "displayDate": "04-10-2014",
    "parsedDate": "2014, 10, 04",
    "startTime": "3:30 pm"
  },
]

  module.exports = matchData